name: 'D365FO Update Model Version'
description: 'This action is using to update version in the AX Model descriptor file.'
branding:
  icon: 'award'  
  color: 'blue'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-id }}
runs:
  using: "composite"
  steps:
    - run: echo Hello ${{ inputs.who-to-greet }}.
    - run: ${{ github.action_path }}/UpdateModelVersion.ps1 -xppSourcePath "C:\_bld\PackagesLocalDirectory" -xppDescriptorSearch "**\Descriptor\*.xml" -xppLayer "VAR" -versionNumber "2.2.30.2"
      shell: powershell
